### ISSUE TITLE
block_regions clarification

### ISSUE THREAD

**Issue by eddielee394** [MonstreX/voyager-site#3]
Can you clarify the usage of the block_regions please?  In the readme [here ](https://github.com/MonstreX/voyager-site#blocks--widgets)it states that the `block_regions` are basically used to group `blocks` and display them in a specific order.  But in the UI, bread settings & on the [Voyager Extension readme](https://github.com/MonstreX/voyager-extension#field-ve-page-layout), they're described as being used to display content from a model field.  
I've experimented with them a bit & they do render the blocks that are associated with the block_region record, but I wanted to be clear of their intended use case.

**Comment by MonstreX** [comment]
Yeah, readme file for voyager-site is not done yet, that's why you cannot find the description of block_regions.
Anyway, block_regions aren't related to the voyager-extension package. It can be used to organize and render a group of blocks whit the same region (group) name whenever you need it in your template.
For instance: 
`{!! render_region('content-before') !!}`
Will render all blocks where this 'content-before' has been set.
And (!) the core will check all blocks if they can be rendered - what depends on the setting "URL paths Rules":
![ScreenClip](https://user-images.githubusercontent.com/1912698/82407590-5840e100-9a8b-11ea-8a50-28b0298bf590.png)

It's a drupal-like block system rendering. That can depend on the current URL or not.

I hope it will help you to understand how it works.

**Comment by eddielee394** [comment]
Ah, that makes total sense now.  Would you be open to the idea of allowing the ability to restrict display to a specific model, in addition to the routes (or allow the user to select which they'd like to apply the rules to?).
For example I'm using the blocks to render content as part of a template builder for various kinds of reports.  Since the report content isn't route specific, but instead model specific it'd be great to have the ability to designate which models (i.e. templates) the regions are allowed to display on.  
I'd be willing to work on the functionality and submit a PR since I've already dug into the source code a bit on both of the packages.

**Comment by MonstreX** [comment]
Sorry, I didn't get clearly what you mean about "model specific".
How can be an individual block relates to a certain model?
To be clear - every block in the region rendering function can be shown or not according to individual block (URL or maybe other) rules. Not a whole region, but every block individually in this region (group). 

> I'd be willing to work on the functionality and submit a PR since I've already dug into the source code a bit on both of the packages.

Yep, you are welcome.

**Comment by MonstreX** [comment]
While the documentation is not completed, this example can help you understand one of main features of block system. 
This block can use their own template (liquid template) and their own data sources directly (without get data somewhere in controllers).
Also, in the template you can use some additional custom filters like 'url', 'crop', 'route', 'block' (to render block inside block), 'form'. Also you can use filter 'func' to call any external function.
![ScreenClip](https://user-images.githubusercontent.com/1912698/82552209-81449d00-9b83-11ea-9b73-45dde2be3e0c.png)

**Comment by eddielee394** [comment]
>Sorry, I didn't get clearly what you mean about "model specific".
How can be an individual block relates to a certain model?

Actually, you can disregard that.  I need to put a little more thought into that specific functionality as I think it may be out of the scope of the package.  

I'll close this out for now.
